server:
  servlet:
    context-path: /bff-soapservice
  port: 8096


service:
  soapServiceUrl: http://localhost:8095/api/soapservice

#security:
#  oauth2:
#    client:
#      clientId: Eduardo
#      clientSecret: admin
#    resource:
#      tokenInfoUri: http://localhost:8030/token-service/api/authenticate

cors:
  allowedOrigins: "https://localhost:8030"

javax:
  xml:
    bind:
      context:
        factory: org.eclipse.persistence.jaxb.JAXBContextFactory

